# Método simplex para resolución de problemas de programación lineal

#### Por [Uriel Allan Aceves Rodríguez](http://www.fciencias.unam.mx/directorio/71726) para la clase de Programación Lineal.
#### Profesora: [Dra. Claudia Orquídea López Soto](http://www.fciencias.unam.mx/directorio/45788).
#### Ayudante: [David Chaffrey Moreno Fernández ](http://www.fciencias.unam.mx/directorio/61894).

## Introducción

El principal algoritmo para la resolución de problemas de programación lineal ha sido por mucho tiempo el *método simplex* introducido por Dantzing. Desde su concepción, el algoritmo a pasado por una evolución sustancial, pero sus principios básicos se han mantenido igual. El método simplex es un procedimiento de cálculos demandantes que requiere el uso de computadoras. Es ampliamente aceptado que la creciente necesidad para la solución de problemas de programación lineal en la vida real ha inspirado significaticamente el desarrollo de las computadoras en la decada de los 50 y principios de los 60 [1].

Desde un punto de vista teórico el método simplex no es necesariamente un algoritmo prometedor dado que en el peor de los casos su complejidad es exponencial [1]. Es decir que el número de iteraciones necesarias para resolver un problema aumenta exponencialmente con el tamaño de la entrada. Han sido creados ejemplos para los cuales el contador de iteraciones del algoritmo alcanza su máximo teórico [2]. En la práctica, sin embargo, el método simplex muestra un rendimiento promedio que es una función lineal del tamaño de la entrada, lo que lo convierte en un método altamente eficiente a la hora de resolver problemas de la vida real.

Entre 1951 y la mitad de la década de los 70 el objetivo principal de los investigadores era mejoras las capacidades computacionales de el método simplex. Cerca del final de dicho periodo se creía que el método simplex había llegado a su madurez y que no valía la pena esforzarse más en él. Sin embargo, a mitad de los 80 la introducción de métodos de punto inferior para resolver el problema de programación lineal revivió el interés en el simplex [1]. Para sorpresa de muchos observadores el método simplex ha logrado un progreso enorme durante su rivalidad con los métodos de punto interior. La ganancia en eficiencia se estima alrededor de dos órdenes de magnitud [2]. Con todo esto en mente podemos pasar a explicar brevemente el problema.

## Explicación sucinta

El algoritmo simplex opera en programas lineales en forma estándar:

$$ \text{maximizar} \quad \mathbf{c} \cdot \mathbf{x} \qquad \qquad \quad$$
$$ \text{s.a}\qquad  \mathbf{Ax} \leq \mathbf{b} \qquad$$
$$ \quad x_i \geq 0 $$

con $x = (x_1, \dots, x_n)$ las variables del problema, $ c = (c_1, \dots, c_n) $ son los coeficientes de la función objetivo, $\mathbf{A}$ una matriz $p\times n$, y $b = (b_1,\dots,b_p)$ constantes con $b_j \geq 0$. Existe un proceso simple para convertir cualquier problema de programación lineal a uno en la forma estándar, de tal manera que esto resulta en ninguna pérdida de generalidad.

En términos geométricos, la región factible

$$ \mathbf{Ax} \leq \mathbf{b}, \quad x_i \geq 0$$

es un (posiblemente no acotado) polítopo convexo. Hay una caracterización simple de los puntos extremos de dicho polítopo,  $x = (x_1,\dots, x_n)$ es un punto extremo si y sólo si el subconjunto de vectores columna $\mathbf{A}_i$ correspondiente a las entradas no nulas de $x$ es linealmente independiente. En éste contexto tal punto es conocido como *solución básica factible*. Puede mostrarse que para un problema lineal en su forma estándar, si la función objetivo tiene un valor máximo en la región factible, entonces alcanza este valor en (por lo menos) uno de los puntos extremos. Esto en si, redice el problema a un cálculo finito dado que existe un número finito de puntos extremos, pero la cantidad de puntos extremos es inmanejablemente largo para todos excepto los problemas más pequeños.

Puede mostrarse además que si un punto extremo no es un punto máximo de la función objetivo entonces existe una arista conteniendo al punto de tal manera que la función objetivo es estrictamente creciente en la arista al alejarse de ese punto. Si la arista es finita entonces conecta con otro punto extremo en que la función objetivo tiene un valor mayor, de otra forma la función objetivo es no acotada en dicha arista y el problema lineal no tiene solución. El algoritmo simplex aplica este razonamiento caminando a lo largo de las aristas del polítopo a puntos extremos con valores objetivo cada vez mayores. Esto continúa hasta que el valor máximo es alcanzado o una arista no acotada es visitada, concluyendo que el problema no tiene solución. El algoritmo siempre termina debido a que el número de vértices del polítopo es finito; además dado que brincamos entre vértices siempre en la misma dirección (la de la función objetivo), esperamos que el número de vértices visitados sea pequeño.

La solución a un problema de programación lineal se alcanza en dos pasos. En el primer paso, conocido como fase I. Se encuentra un punto extremo para iniciar. Dependiendo de la naturaleza del problema, esto puede ser trivial, pero en general puede resolverse aplicando el algoritmo simplex a una versión modificada del problema original. Los posibles resultados de la fase I son encontrar una solución básica factible o que la región factible es vacía. En el segundo caso el problema es llamado *no factible*. En el segundo paso, fase II, el algoritmo simplex es aplicado utilizando la solución básica factible encontrada en la fase I como punto de inicio. Los posibles resultados de la fase II son una solución básica factible óptima o una arista infinita en la cual la función objetivo es no acotada.

## Algoritmo

Sea un problema lineal dado por una tabla canónica. El algoritmo simplex realiza operaciones de pivoteo sucesivas quienes dan una solución básica factible mejorada; la elección del elemento pivote en cada paso es en gran medida determinada por el requerimento de que dicho pivote mejore la solución.

### Elección de la variable entrante

Dado que la variable entrante, en general, incrementará de 0 a un número positivo, el valor de la función objetivo disminuirá si la derivada de la función objetivo con respecto a esa variable es negativa. De manera equivalente, el valor de la función objetivo disminuirá si la columna pivote es seleccionada de tal manera que la entrada corresponeidente en el renglón objetivo de la tabla es positivo.

Si existe más de una columna tal qe la entrada en el renglón objetivo es positivo entonces la elección de cuál agregar al conjunto de variables básicas es de alguna manera arbitrario y varias reglas para la elección de la variable entrante han sido desarrolladas.

Si todas las entradas en el renglón objetivo son menores o iguales que 0 entonces no se puede hacer ninguna elección y la solución es de hehco óptima. Es fácilmente observable que es óptima, debido al hecho de que el renglón objetivo ahora corresponde a una ecuación de la forma

$$ z(\mathbf{x}) = z_B + \text{términos no negativos correspondientes a variables no básicas} $$

Notemos que cambiando la regla de elección para la variable entrante de tal manera que selecciones la entrada negativa en el renglón objetivo, el algoritmo cambiará de tal forma que encuentra el máximo de la función objetivo en lugar de el mínimo.

### Elección de la variable saliente

Una vez que la columna pivote ha sido seleccionada, la elección del renglón pivote es determinado en gran medida por el requerimento de que la solución resultante sea factible. primero, sólo las entradas positivas de la columna pivote son consideradas dado que esto garantiza que el valor de la variable entrante será no negativo. Si no hay entradas positivas en la columna pivote entonces la variable entrante puede tomar cualquier valor no negativo y la solución permanecería factible. En este caso la función objetivo es no acotada por abajo y no existe mínimo.

Después el renglón pivote debe ser seleccionado de tal manera que las variables básicas permanecen positivas. Un cálculo simple muestra que esto ocurre cuando el valor resultante de la variable entrante se encuentra en un mínimo. En otras palabras, si la columna pivote es $c$, entonces el renglón pivote es elegido de tal manera que 

$$ b_r / a_{rc} $$

es el mínimo sobre todas las $r$ de tal manera que $a_{rc} > 0$. Esto se conoce como la prueba del cociente mínimo. Si existe más de un renglón para el cual se alcanza el mínimo entonces puede utilizarse una regla de selección para determinar la variable que entra. En este programa se usa la regla de Bland, que básicamente dice, si hay empate en candidatas a entrar elegimos aquella con el subíndice menor, si hay empate en las candidatas a salir elegimos aquella con el subíndice mayor. Se puede demostrar que con esta regla se previene el ciclado [3-4].

## Programa

### Protocolo previo

Primero es necesario definir el problema que vamos a resolver. Como se comentó arriba, podemos pasar muy fácil de un problema de maximización a uno de minimización y viceversa, en este caso el programa está hecho para resolver problemas de minimización, por lo que si se desear resolver uno de maximización es necesario cambiar la bandera de la variable `minimizar`, a `false`, si el problema es de minimización dicha bandera deberá tener un valor `true`. 

In [1]:
numero_variables = 2
numero_restricciones = 3
minimizar = false

funcion_objetivo = [3,2];

if minimizar == false
    funcion_objetivo = -funcion_objetivo
end

2-element Array{Int64,1}:
 -3
 -2

Generamos la matriz para las restricciones. Es importante comentar el hecho de que la última columna tendrá al vector $\mathbf{b}$ y la penúltima columna está relacionada con el tipo de restricción de dicho renglón, `1` si es de tipo $\leq$, `2` si es de tipo $\geq$ y `3` si es de tipo $=$ (por el momento sólo funciona para restricciones tipo $\leq$).

In [2]:
A = zeros((numero_restricciones, numero_variables + 2))

3x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

Aquí le pasamos las restricciones.

In [3]:
A[1,1:end] = [2,1,1,18]
A[2,1:end] = [2,3,1,42]
A[3,1:end] = [3,1,1,24]

A

3x4 Array{Float64,2}:
 2.0  1.0  1.0  18.0
 2.0  3.0  1.0  42.0
 3.0  1.0  1.0  24.0

La siguiente función se encarga de estandarizar el problema. Poniendo un poco de atención podemos notar que de hecho al hacer esto se crea la misma matriz que en el caso del método de las dos fases. Propiamente no es el método de las dos fases lo que se implementa en este programa pero es muy parecido. Una segunda finalidad de la función `estandarizar` es la de agregar una identidad al final del sistema para poder así hacer comenzar con una base factible.

In [4]:
function estandarizar(A::Array)
    
    columnas_adicionales = numero_restricciones
    
    renglones , columnas  = size(A)
    
    dummy = zeros((renglones, columnas + columnas_adicionales - 1))
    
    dummy[1:renglones, 1:numero_variables] = A[1:renglones, 1:numero_variables]
    
    dummy[1:end,end] = A[1:end,end]
    
    dummy_idx = 1
    
    for i in 1:renglones
        if(A[i,end-1] == 1)
            dummy[i,numero_variables + dummy_idx] = 1.0
            dummy_idx += 1
        end
        if(A[i,end-1] == 2)
            dummy[i,numero_variables + dummy_idx] = -1.0
            dummy_idx += 1
        end
    end
    
    println("La nueva matriz de restricciones es:")
    println(dummy)
    
    return dummy
    
end

estandarizar (generic function with 1 method)

Después de estandarizar la matriz de nuestro problema (y de remover la columna relacionada con el tipo de restricción) las cosas quedarían así

In [5]:
A = estandarizar(A);

La nueva matriz de restricciones es:
[2.0 1.0 1.0 0.0 0.0 18.0
 2.0 3.0 0.0 1.0 0.0 42.0
 3.0 1.0 0.0 0.0 1.0 24.0]


## Método simplex

Entrando ahora sí al algoritmo simplex, definimos la matriz B que guardará la base y guardamos al vector b.

In [6]:
B = zeros((numero_restricciones,numero_restricciones))

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [7]:
b = A[1:end,end]

3-element Array{Float64,1}:
 18.0
 42.0
 24.0

Llenamos el vector de costos

In [8]:
vector_costos = zeros(size(A)[2]-1)

for i in 1:numero_variables
    vector_costos[i] = funcion_objetivo[i]
end

vector_costos

5-element Array{Float64,1}:
 -3.0
 -2.0
  0.0
  0.0
  0.0

Hacemos una función para, dado el vector de variables básicas obtener el vector de variables no básicas

In [9]:
function obtener_no_basicas(variables_basicas)
   
    no_b = zeros(size(A)[2] - 1 - numero_restricciones)
    
    idx = 1
    
    for i in 1:(size(A)[2] - 1)
        
        contador = 0
        
        for j in variables_basicas
            if j != i
                contador += 1
            end
        end
        
        if contador == numero_restricciones
            no_b[idx] = i
            idx += 1
        end
        
    end
    
    return no_b
    
end

obtener_no_basicas (generic function with 1 method)

Implementamos una función para obtener la nueva base.

In [10]:
function nueva_base(variables_basicas,entra,sale)
   
    idx = 1
    
    for i in variables_basicas
        if sale == i
            variables_basicas[idx] = entra
            break
        end
        idx += 1
    end
    
    return variables_basicas
    
end

nueva_base (generic function with 1 method)

Definimos una función para elegir la variable entrante, de acuerdo con la regla de Bland.

In [11]:
function quien_sale(a_i, b_barra)
    
    dummy = zeros(numero_restricciones)
    
    for i in 1:numero_restricciones
        if a_i[i] > 0
            dummy[i] = b_barra[i]/a_i[i]
        else
            dummy[i] = Inf
        end
    end 
    
    min = minimum(dummy)
    
    for i in 0:numero_restricciones-1
        if dummy[numero_restricciones - i] == min
            return numero_restricciones - i
            break
        end
    end
    
end    

quien_sale (generic function with 1 method)

Hacemos una función que hace **una** iteración en el algoritmo simplex.

In [12]:
function iteracion_simplex(variables_basicas)
    
    B[1:end,1] = A[1:end,variables_basicas[1]]
    B[1:end,2] = A[1:end,variables_basicas[2]]
    B[1:end,3] = A[1:end,variables_basicas[3]]
    
    A_dummy = *(inv(B),A)
    
    println("=================================================================================================")
    println("El sistema en esta iteración es:")
    println(A_dummy)
    
    x_b = variables_basicas
    c_b = [vector_costos[x_b[1]],vector_costos[x_b[2]],vector_costos[x_b[3]]]
    b_barra = *(inv(B),b)
    
    costos_reducidos = *(*(c_b',inv(B)),A[1:end,1:end-1]) - vector_costos'
    
    println()
    println("El vector de costos reducidos en esta iteración es:")
    println(costos_reducidos)
    println()
    
    sale = 0
    entra = 0
    
    variables_no_basicas = obtener_no_basicas(x_b)
    
    idx = 0
    
    for i in variables_no_basicas
        
        if costos_reducidos[i] <= 0
            idx += 1
        end
        
    end
    
    
    factor = 1
    
    if minimizar == false
        factor = -1
    end
    
    objetivo = c_b⋅b_barra*factor
    
    if idx == size(A)[2] - 1 - numero_restricciones
        println("=================================================================================================")
        println("Llegué al óptimo, es: ", objetivo)
        return 0
    end
    
    for i in variables_no_basicas
        
        if costos_reducidos[i] > 1e-8
            
            entra = i
            
            break   
            
        end
        
    end
    
    for i in 1:numero_restricciones
        
        idx = 0
        
        if A_dummy[i,entra] <= 0
            idx += 1
        end
        
        if idx == numero_restricciones
            println("El problema es no acotado. Me largo de aquí.")
            return 0
        end
        
    end
    
    sale = variables_basicas[quien_sale(A_dummy[1:end,entra],b_barra)]

    println("La variable que entra es la: ",entra)
    println("La variable que sale  es la: ",sale)
    
    base_actualizada = nueva_base(variables_basicas,entra,sale)
    
    return base_actualizada
    
end

iteracion_simplex (generic function with 1 method)

Definimos el ciclo principal, que se detiene al momento de llegar a la solución óptima.

In [13]:
base = zeros(numero_restricciones)

for i in 1:numero_restricciones
    
    base[i] = numero_variables + i
    
end

while base != 0

    base = iteracion_simplex(base)

end

El sistema en esta iteración es:
[2.0 1.0 1.0 0.0 0.0 18.0
 2.0 3.0 0.0 1.0 0.0 42.0
 3.0 1.0 0.0 0.0 1.0 24.0]

El vector de costos reducidos en esta iteración es:
[3.0 2.0 0.0 0.0 0.0]

La variable que entra es la: 1.0
La variable que sale  es la: 5.0
El sistema en esta iteración es:
[0.0 0.33333333333333337 1.0 0.0 -0.6666666666666666 2.0
 0.0 2.3333333333333335 0.0 1.0 -0.6666666666666666 26.0
 1.0 0.3333333333333333 0.0 0.0 0.3333333333333333 8.0]

El vector de costos reducidos en esta iteración es:
[0.0 1.0 0.0 0.0 -1.0]

La variable que entra es la: 2.0
La variable que sale  es la: 3.0
El sistema en esta iteración es:
[0.0 0.9999999999999996 3.0 -1.1102230246251565e-16 -2.0 5.999999999999993
 0.0 -8.881784197001252e-16 -7.0 0.9999999999999998 4.0 12.0
 1.0 0.0 -1.0 0.0 1.0 6.0]

El vector de costos reducidos en esta iteración es:
[0.0 8.881784197001252e-16 -3.0 2.220446049250313e-16 1.0]

La variable que entra es la: 5.0
La variable que sale  es la: 4.0
El sistema en esta iterac

## Referencias


* [1] István Maros, *Computational Techniques of the Simplex Method*, Springer Science & Business Media, 2012.
* [2] Dieter Jungnickel, *Graphs, Networks and Algorithms*, Springer Science & Business Media, 2007.
* [3] Horst Peters, *Wirtschaftsmathematik: Lehrbuch*, W. Kohlhammer Verlag, 2009.
* [4] 徐渝, 贾涛, *运筹学*, 清华大学出版社有限公司, 2005.
* [5] George Bernard Dantzig, *Origins of the Simplex Method*, Defense Technical Information Center, 1987.
* [6] Thomas Bradtke, *Grundlagen in Operations Research für Ökonomen*, Oldenbourg Verlag, 2003.
* [7] Bernd Luderer, Volker Nollau, Klaus Vetters, *Mathematische Formeln für Wirtschaftswissenschaftler*, Springer-Verlag, 2015.
* [8] *运筹学教程*, 清华大学出版社有限公司, 1990. 